name: siamese
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - matplotlib==3.3.1
  - pandas==1.1.0
  - requests==2.24.0
  - scikit-learn==0.23.2
  - flask==1.1.2
  - joblib=0.16.0
  - cudatoolkit=10.1
  - cudnn=7.6
  - pip=20.0
  - python=3.8
  - pip:
      - requests-html
      - google-cloud-storage
      - google-api-python-client
      - google-auth
      - google-auth-httplib2
      - tensorflow
      - Pillow
      - imutils
      - opencv-python
      - tensorflow
